blank_issues_enabled: false

contact_links:
  - name: Project Documentation
    url: https://github.com/Kallappa2005/MLOPS_RED_WINE_QUALITY_PREDICTION
    about: Please review the project documentation before creating an issue.